version: "3.8"
services:
  # PHP service
  app:
    build: ./docker/php/.
    container_name: flexi-php
    working_dir: /var/www/site
    volumes:
      - ./site:/var/www/site
    networks:
      - flexi-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: flexi-nginx
    working_dir: /var/www/site
    ports:
      - 8001:80
    volumes:
      - ./site:/var/www/site
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - flexi-network

  # Mysql service
  mysql:
    image: mysql:5.7.22
    container_name: flexi-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=flexi
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=apppass
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 8982:3306
    networks:
      - flexi-network

networks:
  flexi-network:
    driver: bridge